site:
  name: SMD Vital Bogota
  site: 'https://smdvitalbogota.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: 2HVWH3O2ShwC1GMYvEtBd6fbgBe3RryOJNnIWz3SYKs

# Metadatos SEO predeterminados
metadata:
  title:
    default: 'SMD Vital Bogota'
    template: '%s — SMD Vital Bogota'
  description: '🚀 Nuestros médicos a domicilio en Bogotá ofrecen atención médica de calidad en la comodidad de tu hogar. Olvídate del tráfico y las largas esperas en salas de espera, ¡contáctanos!'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: SMD Vital Bogota
    images:
      - url: '~/assets/images/hero-image.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@SMDVitalBogota'
    site: '@SMDVitalBogota'
    cardType: summary_large_image

# Configuración de internacionalización (idioma)
i18n:
  language: es
  textDirection: ltr

# Configuración del blog
apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category% (Ajusta la estructura de las URL de las publicaciones)
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Ruta principal del blog, puedes cambiar esto a "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'categoria' # Ruta principal de categorías /category/some-category, puedes cambiar esto a "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'etiqueta' # Ruta principal de etiquetas /tag/some-tag, puedes cambiar esto a "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

# Configuración de analíticas
analytics:
  vendors:
    googleAnalytics:
      id: G-C4842C2XKM # o ""

# Configuración de la interfaz de usuario
ui:
  theme: 'system' # Valores: "system" | "light" | "dark" | "light:only" | "dark:only"
